public with sharing class dataTableRow {
	
	public String item1 {get; set;}
	public String item2 {get; set;}
	public String item3 {get; set;}
	public String item4 {get; set;}
	//public String item5 {get; set;}
	//public String item6 {get; set;}
	//public String item7 {get; set;}
	public String item8 {get; set;}
	public String item9 {get; set;}
	public String item10 {get; set;}
	
	public dataTableRow()
	{
		
	}
}