public with sharing class GenericTableRow {
	
	public string value0 {get; set;}
	public string value1 {get; set;}
	public string value2 {get; set;}
	public string value3 {get; set;}
	public string value4 {get; set;}
	public string value5 {get; set;}
	public string value6 {get; set;}
	public string value7 {get; set;}
	public string value8 {get; set;}
	public string value9 {get; set;}
	public decimal value10 {get; set;}
	
	public GenericTableRow() 
	{
		
	}
}