@isTest
private class TestTimesheetMethods {
    static testMethod void testTimesheetBeforeTrigger() {
        /*
    	Account testAccount = new Account();
		testAccount.Name = 'test';
		testAccount.Phone = '111-222-3334';
		testAccount.Type = 'Standard Price Book';
		Database.insert(testAccount);	
		
    	Project__c testProject = new Project__c();
    	testProject.Account__c = testAccount.Id;
    	Database.insert(testProject);

    	Requirement__c testRequirement = new Requirement__c();
    	testRequirement.Description__c = 'test';
    	testRequirement.Subject__c = 'test';
    	testRequirement.Project__c = testProject.Id;
    	Database.insert(testRequirement);
    	
        Time_Sheet__c testTimeSheet = new Time_Sheet__c();
		testTimeSheet.Date__c = Date.today();
        //testTimeSheet.Requirement__c = testRequirement.Id;
		testTimeSheet.Configuration_Minutes__c = 15;
		testTimeSheet.Design_Minutes__c = 15;
		testTimeSheet.Development_Minutes__c = 15;
		testTimeSheet.Documentation_Minutes__c = 15;
		testTimeSheet.Project_Management_Minutes__c = 15;
		testTimeSheet.Reporting_Minutes__c = 15;
		testTimeSheet.Testing_Minutes__c = 15;
		testTimeSheet.Training_Minutes__c = 15;
		
		testTimeSheet.Configuration_Hours__c = 2;
		testTimeSheet.Design_Hours__c = 2;
		testTimeSheet.Development_Hours__c = 2;
		testTimeSheet.Documentation_Hours__c = 2;
		testTimeSheet.Project_Management_Hours__c = 2;
		testTimeSheet.Reporting_Hours__c = 2;
		testTimeSheet.Testing_Hours__c = 2;
		testTimeSheet.Training_Hours__c = 2;
		
		Database.insert(testTimeSheet);
		testTimeSheet = [select Total_Hours__c from Time_Sheet__c where Id = :testTimeSheet.Id];
		//System.assertEquals(testTimeSheet.Total_Hours__c, 22.5);
		
		Product2 testProduct = new Product2();
		testProduct.Base_Price__c = 100;
		testProduct.Description = 'test';
		testProduct.Name = 'test';
		testProduct.ProductCode = 'test';
		Database.insert(testProduct);
*/
    }
}